articulo_actualidad:
    pattern:  /actualidad/
    defaults: { _controller: ArticuloBundle:Articulo1:Actualidad }
        
articulo_archivo:
    pattern:  /archivo/
    defaults: { _controller: ArticuloBundle:Articulo1:Archivo }
    
articulo_articulo:
    pattern:  /articulo/{slug}/
    defaults: { _controller: ArticuloBundle:Articulo1:Articulo }
